/**
 * Do not edit this file unless you know what you're doing.
 */

#include "build-gen.h"

#ifdef IPOIRC_BUILD_LIBIRCCLIENT_LIBIRCCLIENT
#    include <libircclient/libircclient.h>
#elif defined(IPOIRC_BUILD_LIBIRCCLIENT)
#    include <libircclient.h>
#else
#    error "failed to include libircclient"
#endif
