/**
 * Do not edit this file unless you know what you're doing.
 */

#include "build-gen.h"

#ifdef IPOIRC_BUILD_DUMBNET
#    include <dumbnet.h>
#elif defined(IPOIRC_BUILD_DNET)
#    include <dnet.h>
#else
#    error "failed to include dnet"
#endif
